---
- name: Install nomad
  hosts: servers
  become: yes
  tasks:
    - name: Ensure nomad can set memory quotas on exec drivers via cgroup
      ansible.builtin.replace:
        regexp: '^.*rootwait(?! cgroup_enable=memory)$'
        replace: "\1 cgroup_enable=memory"
        path: "/boot/cmdline.txt"
    - name: Get nomad agent binary
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/nomad_1.1.4_linux_arm.zip
        dest: /usr/local/bin
        mode: 0744
    - name: Get consul binary
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/consul_1.10.4_linux_arm.zip
        dest: /usr/local/bin
        mode: 0744
    - name: Ensures /etc/nomad exists
      file:
        path: /etc/nomad
        mode: 0744
        state: directory
    - name: Install server config file
      ansible.builtin.copy:
        src: server.hcl
        dest: /etc/nomad/
        mode: 0444
    - name: Ensure /opt/cni/bin exists
      file:
        path: /opt/cni/bin
        mode: 0744
        state: directory
    - name: Install client cni plugins
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/cni-plugins-linux-arm-v1.0.0.tar
        dest: /opt/cni/bin
        mode: 0744
    - name: Install server service
      ansible.builtin.copy:
        src: nomad-server.service
        dest: /etc/systemd/system
        mode: 0744
    - name: Ensure /etc/consul exists
      file:
        path: /etc/consul.d
        mode: 0744
        state: directory
    - name: Install consul config file
      ansible.builtin.copy:
        src: consul.json
        dest: /etc/consul.d/
        mode: 0444
    - name: Install consul service
      ansible.builtin.copy:
        src: consul.service
        dest: /etc/systemd/system
        mode: 0444
    - name: Start consul server
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: consul.service
        enabled: yes
    - name: Start nomad server
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: nomad-server.service
        enabled: yes
