---
- name: Install nomad
  hosts: servers
  become: yes
  tasks:
    - name: Get nomad agent binary
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/nomad_1.1.4_linux_arm.zip
        dest: /usr/local/bin
        mode: 0744
    - name: Get consul binary
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/consul_1.10.4_linux_arm.zip
        dest: /usr/local/bin
        mode: 0744
    - name: Ensures /etc/nomad exists
      file:
        path: /etc/nomad
        mode: 0744
        state: directory
    - name: Install server config file
      ansible.builtin.copy:
        src: server.hcl
        dest: /etc/nomad/
        mode: 0444
    - name: Install server service
      ansible.builtin.copy:
        src: nomad-server.service
        dest: /etc/systemd/system
        mode: 0744
    - name: Ensure /etc/consul exists
      file:
        path: /etc/consul
        mode: 0744
        state: directory
    - name: Install consul config file
      ansible.builtin.copy:
        src: consul.json
        dest: /etc/consul/
        mode: 0444
    - name: Install consul service
      ansible.builtin.copy:
        src: consul.service
        dest: /etc/systemd/system
        mode: 0744
    - name: Start consul server
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: consul.service
    - name: Start nomad server
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: nomad-server.service
