---
- name: Install nomad
  hosts: all
  become: yes
  tasks:
    - name: Copy extract and install nomad
      get_url:
        url: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/nomad_1.1.4_linux_arm.zip
        dest: /usr/local/bin
        mode: 0755
