---
- name: Install nomad client
  hosts: clients
  become: yes
  tasks:
    - name: Get nomad agent binary
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/nomad_1.1.4_linux_arm.zip
        dest: /usr/local/bin
        mode: 0744
    - name: Get consul binary
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/consul_1.10.4_linux_arm.zip
        dest: /usr/local/bin
        mode: 0744
    - name: Ensures /etc/nomad exists
      file:
        path: /etc/nomad
        mode: 0744
        state: directory
    - name: Install client config file
      ansible.builtin.copy:
        src: client.hcl
        dest: /etc/nomad/
        mode: 0444
    - name: Ensure /opt/cni/bin exists
      file:
        path: /opt/cni/bin
        mode: 0744
        state: directory
    - name: Install client cni plugins
      unarchive:
        remote_src: yes
        src: https://github.com/m-rios/rpi-cluster/releases/download/v0.0.0/cni-plugins-linux-arm-v1.0.0.tar
        dest: /opt/cni/bin
        mode: 0744
    - name: Install client service
      ansible.builtin.copy:
        src: nomad-client.service
        dest: /etc/systemd/system
        mode: 0744
    - name: Ensure /etc/consul exists
      file:
        path: /etc/consul.d
        mode: 0744
        state: directory
    - name: Install consul config file
      ansible.builtin.template:
        src: consul-client.json
        dest: /etc/consul.d/consul.json
        mode: 0444
    - name: Install consul service
      ansible.builtin.copy:
        src: consul.service
        dest: /etc/systemd/system
        mode: 0444
    - name: Start consul client 
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: consul.service
    - name: Start nomad client 
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted 
        name: nomad-client.service
