---
- name: NAS
  hosts: cluster
  become: yes
  tasks:
    - name: Create mount directory
      ansible.builtin.file:
        group: pi
        owner: pi
        path: /media/storage
        state: directory
        mode: 0755
    - name: Install ntfs,nfs
      apt:
        name: ntfs-3g,nfs-kernel-server
        update-cache: yes
    - name: Mount storage directory
      ansible.posix.mount:
        path: /mnt/storage
        src: /dev/sda4
        opts: uid=pi,gid=pi
        state: mounted
        fstype: ntfs
    - name: Create NFS export config
      copy:
        dest: |
          /etc/export
        content: /mnt/storage 192.168.1.0/24 (rw,sync,no_subtree_check)
    - name: Export the FS
      command: exportfs -a
    - name: Restart nfs-kernel-server.service 
      ansible.builtin.systemd:
        daemon_reload: yes
        state: started
        name: nfs-kernel-server.service
    - name: Restart rpc-statd
      ansible.builtin.systemd:
        daemon_reload: yes
        state: started
        name: rpc-statd.service
