version: '3.4'
services:
  traefik:
    container_name: traefik
    image: traefik:v2.7
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks: 
  default: 
    external: 
      name: traefik

